version: "3.9"

x-env: &env   
    env_file:
      - ${ENV_FILE:-.env}
services:
  db:  
    <<: [*env]
    image: postgres:15.3-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - botdb-data:/var/lib/postgresql/data


volumes:
  botdb-data: